//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpClass23IT4
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanVien()
        {
            this.hopDongs = new HashSet<hopDong>();
        }
    
        public string maNhanVien { get; set; }
        public string ten { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string gioiTinh { get; set; }
        public Nullable<int> SDTnv { get; set; }
        public string diaChinv { get; set; }
        public string chucVu { get; set; }
        public Nullable<int> bacLuong { get; set; }
        public string maPB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hopDong> hopDongs { get; set; }
        public virtual phongBan phongBan { get; set; }
    }
}
