//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpFiletxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class phongBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phongBan()
        {
            this.nhanViens = new HashSet<nhanVien>();
        }
    
        public string maPB { get; set; }
        public string tenPB { get; set; }
        public Nullable<int> SDTpb { get; set; }
        public string diaDiempb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhanVien> nhanViens { get; set; }
    }
}
